[pytest]
# תיקיית הטסטים
testpaths = tests

# הגדרות הרצה אוטומטיות (חוסך לכתוב --headed כל פעם)
addopts = 
    --headed 
    --browser chromium
    --screenshot only-on-failure
    --video retain-on-failure

# הגדרת נתיב הפרויקט כדי שלא תצטרך $env:PYTHONPATH בטרמינל
pythonpath = .

# התעלמות מאזהרות asyncio ישנות
filterwarnings =
    ignore::pytest.PytestConfigWarning
